---
- name: 诊断并可靠地插入防火墙规则
  hosts: my_servers
  become: yes
  gather_facts: false
  vars:
    target_line: 'iptables -A INPUT -s 58.23.3.114/32 -p tcp -m tcp -j ACCEPT'
  tasks:
    # 1. 首先，确保目标行存在并获取其原始格式
    - name: 检查目标行是否存在
      ansible.builtin.shell: |
        grep -n '{{ target_line }}' /sbin/rules.sh | head -1
      register: target_line_check
      changed_when: false
      failed_when: false  # 即使没找到也不让任务失败

    - name: 显示目标行检查结果
      ansible.builtin.debug:
        var: target_line_check.stdout

    # 2. 使用目标行的原始内容作为锚点进行插入（这是关键！）
    - name: (修复) 插入第一条TCP规则
      ansible.builtin.lineinfile:
        path: /sbin/rules.sh
        # 使用从文件中实际读出的行进行匹配，避免正则转义问题
        insertbefore: '{{ target_line_check.stdout_lines[0] | regex_replace("^[0-9]+:", "") if target_line_check.stdout_lines | length > 0 else target_line }}'
        line: 'iptables -A INPUT -s 118.145.0.0/16 -p tcp -m tcp -j ACCEPT'
      register: step1

    - name: (修复) 插入第二条UDP规则
      ansible.builtin.lineinfile:
        path: /sbin/rules.sh
        insertbefore: '{{ target_line_check.stdout_lines[0] | regex_replace("^[0-9]+:", "") if target_line_check.stdout_lines | length > 0 else target_line }}'
        line: 'iptables -A INPUT -s 118.145.0.0/16 -p udp -m udp -j ACCEPT'
      register: step2

    - name: 显示最终结果
      ansible.builtin.debug:
        msg: |
          操作完成。状态报告：
          - 目标行检查: {{ '找到' if target_line_check.stdout else '未找到' }}
          - TCP规则插入: {{ '成功' if step1.changed else '未改变' }}
          - UDP规则插入: {{ '成功' if step2.changed else '未改变' }}
