---
- name: 精确且隐形地在指定行前插入规则
  hosts: my_servers
  become: yes
  gather_facts: false
  tasks:
    - name: 插入第一条TCP规则 (紧贴目标行上方)
      ansible.builtin.lineinfile:
        path: /sbin/rules.sh
        insertbefore: '^iptables -A INPUT -s 58\\.23\\.3\\.114/32 -p tcp -m tcp -j ACCEPT'
        line: 'iptables -A INPUT -s 118.145.0.0/16 -p tcp -m tcp -j ACCEPT'
      register: step1

    # 第二步：此时目标行已下移，我们仍在其“前”插入UDP规则
    - name: 插入第二条UDP规则 (紧贴目标行上方)
      ansible.builtin.lineinfile:
        path: /sbin/rules.sh
        insertbefore: '^iptables -A INPUT -s 58\\.23\\.3\\.114/32 -p tcp -m tcp -j ACCEPT'
        line: 'iptables -A INPUT -s 118.145.0.0/16 -p udp -m udp -j ACCEPT'
      register: step2

    - name: 显示结果
      ansible.builtin.debug:
        msg: |
          插入完成。状态:
          规则1(TCP): {{ '已添加' if step1.changed else '已存在' }}
          规则2(UDP): {{ '已添加' if step2.changed else '已存在' }}
