---
- name: 在所有服务器上查询指定IP规则
  hosts: my_servers  # 请确保清单中已定义此组
  gather_facts: false  # 此任务无需收集系统信息，可关闭以加快速度
  tasks:
    - name: 在 /sbin/rules.sh 中查找包含 58.23.3.114/32 的行
      ansible.builtin.shell: |
        cat /sbin/rules.sh 2>/dev/null | grep -- "58.23.3.114/32" || echo "文件不存在或未找到匹配项"
      register: grep_result  # 将命令结果保存到变量中
      ignore_errors: true    # 即使命令失败（如文件不存在）也继续执行
      changed_when: false    # 此命令为查询操作，不会改变系统状态，输出始终为“OK”

    - name: 打印查询结果
      ansible.builtin.debug:
        msg: |
          主机: `{{ inventory_hostname }}`
          查询结果:
          {{ grep_result.stdout_lines | default([]) | join('\n') }}
